spring:
  ai:
    vectorstore:
      milvus:
        client:
          secure: 'true'
          token: ${milvusToken}
          uri: https://in03-bd46d1d258c4323.api.gcp-us-west1.zillizcloud.com
        collectionName: page_views
        embeddingDimension: '1536'
        metricType: COSINE
    openai:
      temperature: '0.8'
      completion:
        choices:
          number: '3'
      maxTokens: '180'
      api-key: ${openaiToken}


deltastream:
  token: ${deltastreamToken}
  default:
    role: orgadmin
  organization:
    id: d377518a-452b-4441-bf2e-90f8c3490da7
  databaseName: mohinish_sid
  materialView: cc_mv
  api:
    url: https://api.deltastream.io

